### ISSUE TITLE
set TimeZone in container

### ISSUE THREAD

**Issue by osipovaleks** [levonet/docker-rsyslog#1]
Hi! Thank you for the wonderful image! 
I have just one question.

How do I change the time zone inside a running container correctly?

The variant with `-e TZ=Europe/Kiev` did not help in any way. 
There is no `/etc/timezone` directory inside the container and I can't mapping it off the host.

Maybe we can add `apk add tzdata` to Dockerfile?

**Comment by levonet** [comment]
The size of the `tzdata` package is quite large. Not sure it needs for me and those few others who use this image.

I propose you make your own image
```dockerfile
FROM levonet/rsyslog:latest

RUN apk add --no-cache tzdata
```

**Comment by levonet** [comment]
Another way you can try to mount local `/usr/share/zoneinfo` into container.

**Comment by osipovaleks** [comment]
Thank you for your answers, I will make my own image.

**Comment by osipovaleks** [comment]
I made my image, just added an `tzdata` - maybe someone could use it -[https://hub.docker.com/r/osipovaleks/rsyslog](https://hub.docker.com/r/osipovaleks/rsyslog)
